name: Build Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Create Windows package
      run: npm run package
      
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v2
      with:
        name: spotify-cli-windows
        path: spotify-cli-win.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Create Debian package
      run: npm run package
      
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v2
      with:
        name: spotify-cli-linux
        path: spotify-cli_1.0.0_amd64.deb 